In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Step 1: Import the required libraries


In [3]:
insurance = pd.read_csv("Medical_insurance_dataset.csv")

In [4]:
insurance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    object
dtypes: int64(3), object(2)
memory usage: 15.8+ KB


In [5]:
insurance["Gender"] = insurance["Gender"].replace({"Male": 1, "Female": 0})

In [6]:
insurance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    int64 
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    object
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [7]:
insurance.head()

User ID  Gender  Age  EstimatedSalary      Purchased
0  15624510       1   19            19000  not-purchased
1  15810944       1   35            20000  not-purchased
2  15668575       0   26            43000  not-purchased
3  15603246       0   27            57000  not-purchased
4  15804002       1   19            76000  not-purchased

In [8]:
insurance["Purchased"] = insurance["Purchased"].replace({"purchased": 1, "not-purchased": 0})

In [9]:
insurance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          400 non-null    int64
 1   Gender           400 non-null    int64
 2   Age              400 non-null    int64
 3   EstimatedSalary  400 non-null    int64
 4   Purchased        400 non-null    int64
dtypes: int64(5)
memory usage: 15.8 KB


In [10]:
insurance.drop("User ID", inplace = True, axis = 1)

In [11]:
insurance.head()

Gender  Age  EstimatedSalary  Purchased
0       1   19            19000          0
1       1   35            20000          0
2       0   26            43000          0
3       0   27            57000          0
4       1   19            76000          0

In [12]:
insurance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           400 non-null    int64
 1   Age              400 non-null    int64
 2   EstimatedSalary  400 non-null    int64
 3   Purchased        400 non-null    int64
dtypes: int64(4)
memory usage: 12.6 KB


# Preparing the Data for modeling
X is called Input (Age, Gender, Estimated Salary)
y is output (Purchase column)
X train is the train dataset input
X test is the test dataset input
y train is the train output
t test is the test output

In [13]:
# Importing models
from sklearn import metrics  # Model for valuation metrics
from sklearn.model_selection import train_test_split # Module for splitting

In [14]:
# Separating features(input) and the label from the data
X = insurance.drop("Purchased", axis = "columns") # Dropping the purchased column in order to make the X only the input dataset

In [15]:
X.head()

Gender  Age  EstimatedSalary
0       1   19            19000
1       1   35            20000
2       0   26            43000
3       0   27            57000
4       1   19            76000

In [16]:
y = insurance["Purchased"] # Equating y to purchased in order to make y the output dataset

In [17]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Purchased, dtype: int64

In [47]:
y_train

199    0
43     0
307    1
166    0
64     0
      ..
241    0
253    1
390    1
155    0
331    1
Name: Purchased, Length: 320, dtype: int64

### Methods of Encoding
#### 1. One Hot Encoding
#### 2. LAbel Encoding
#### 3. LAbel Binarizer
#### 4. Get Dummies

In [18]:
# Get Dummies - automatically create a dummy channel for each category

In [19]:
# X_train. X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1234, shuffle = True)

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 12, shuffle = True)

In [21]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(320, 3)
(80, 3)
(320,)
(80,)


In [22]:
# Model Training
# Importing the model
# Instantiating the model(giving it a variable)
# Fitting/Training the model
# Predicting the test dataset
# saving the prediction into another variable
# Calculating the accuracing score



# Importing the algorithm

from sklearn.linear_model import LogisticRegression

In [23]:
# Instantiating the model(giving it a variable)
logisticmodel = LogisticRegression()

In [24]:
# Fitting/Training the model
logisticmodel.fit(X_train, y_train)

LogisticRegression()

In [25]:
# Predicting the test dataset
logisticmodel.predict(X_test)

array([1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [26]:
y_train

199    0
43     0
307    1
166    0
64     0
      ..
241    0
253    1
390    1
155    0
331    1
Name: Purchased, Length: 320, dtype: int64

In [27]:
# saving the prediction into another variable
logistic_prediction = logisticmodel.predict(X_test)

In [28]:
logistic_prediction[:10]

array([1, 0, 1, 0, 0, 1, 0, 0, 1, 0], dtype=int64)

In [29]:
y_test[:10]

280    1
387    0
313    1
1      0
35     0
210    1
39     0
52     0
320    1
231    0
Name: Purchased, dtype: int64

In [30]:
# Calculating the accuracing score
from sklearn.metrics import accuracy_score

In [31]:
accuracy_score(y_test, logistic_prediction) * 100

71.25

In [32]:
# Hyper-parameter tuning

In [33]:
# Building another model

# importing a model
from sklearn.naive_bayes import GaussianNB

# Instantiating the model
naivemodel = GaussianNB()

#training the dataset
naivemodel.fit(X_train, y_train)

# predicting the dataset
naivemodel.predict(X_test)

# Giving the prediction a variable
naive_prediction = naivemodel.predict(X_test)



In [34]:
naive_prediction

array([1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0], dtype=int64)

In [35]:
y_test

280    1
387    0
313    1
1      0
35     0
      ..
149    0
301    1
78     0
71     0
186    0
Name: Purchased, Length: 80, dtype: int64

In [36]:
# Calculating the accuracy score
accuracy_score(y_test, naive_prediction) * 100

85.0

In [37]:
# Building another model

# importing a model
from sklearn.ensemble import RandomForestClassifier

# Instantiating the model
randomforestmodel = RandomForestClassifier()

#training the dataset
randomforestmodel.fit(X_train, y_train)

# predicting the dataset
randomforestmodel.predict(X_test)

# Giving the prediction a variable
random_prediction = naivemodel.predict(X_test)

In [38]:
accuracy_score(y_test, random_prediction) * 100

85.0

In [39]:
# Building another model

# importing a model
from sklearn.svm import SVC

# Instantiating the model
SVMmodel = SVC()

#training the dataset
SVMmodel.fit(X_train, y_train)

# predicting the dataset
SVMmodel.predict(X_test)

# Giving the prediction a variable
Sprediction = SVMmodel.predict(X_test)

In [40]:
accuracy_score(y_test, Sprediction) * 100

72.5

In [41]:
# f1 score for logistics Regression

from sklearn.metrics import accuracy_score, f1_score
f1_score(y_test, logistic_prediction)


0.634920634920635

In [42]:
# f1 score for GuassianNB
f1_score(y_test, naive_prediction)

0.823529411764706

In [43]:
# f1 score for random tree
f1_score(y_test, random_prediction)

0.823529411764706

In [44]:
# f1 score for SVC
f1_score(y_test, Sprediction)

0.56

In [45]:
y_train

199    0
43     0
307    1
166    0
64     0
      ..
241    0
253    1
390    1
155    0
331    1
Name: Purchased, Length: 320, dtype: int64