In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [68]:
insurance = pd.read_csv("Medical_insurance_dataset.csv")
pokemonData = pd.read_excel("pokemon_data.xlsx")

In [4]:
insurance.head()

User ID  Gender  Age  EstimatedSalary      Purchased
0  15624510    Male   19            19000  not-purchased
1  15810944    Male   35            20000  not-purchased
2  15668575  Female   26            43000  not-purchased
3  15603246  Female   27            57000  not-purchased
4  15804002    Male   19            76000  not-purchased

In [8]:
insurance.drop("User ID", inplace = True, axis = "columns")

In [9]:
insurance.head()

Gender  Age  EstimatedSalary      Purchased
0    Male   19            19000  not-purchased
1    Male   35            20000  not-purchased
2  Female   26            43000  not-purchased
3  Female   27            57000  not-purchased
4    Male   19            76000  not-purchased

In [11]:
insurance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Gender           400 non-null    object
 1   Age              400 non-null    int64 
 2   EstimatedSalary  400 non-null    int64 
 3   Purchased        400 non-null    object
dtypes: int64(2), object(2)
memory usage: 12.6+ KB


In [12]:
insurance["Gender"] = insurance["Gender"].replace({"Male": 1, "Female": 0})

In [13]:
insurance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Gender           400 non-null    int64 
 1   Age              400 non-null    int64 
 2   EstimatedSalary  400 non-null    int64 
 3   Purchased        400 non-null    object
dtypes: int64(3), object(1)
memory usage: 12.6+ KB


In [14]:
insurance["Purchased"] = insurance["Purchased"].replace({"purchased": 1, "not-purchased": 0})

In [15]:
insurance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           400 non-null    int64
 1   Age              400 non-null    int64
 2   EstimatedSalary  400 non-null    int64
 3   Purchased        400 non-null    int64
dtypes: int64(4)
memory usage: 12.6 KB


In [59]:
#Import metrics
# Model Training
# Logistics Regression
# Instantiating the model(giving it a variable)
# Fitting/Training the model
# Predicting the test dataset
# saving the prediction into another variable
# Calculating the accuracing score


from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import accuracy_score, f1_score


In [19]:
X = insurance.drop("Purchased", axis = "columns")

In [98]:
y = ""

In [67]:
y_train

82     0
367    1
179    0
27     1
89     0
      ..
255    1
72     0
396    1
235    1
37     0
Name: Purchased, Length: 300, dtype: int64

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = True, shuffle = 1234, test_size = 0.25)

In [30]:
# Building a model
from sklearn.linear_model import LogisticRegression
logic = LogisticRegression()

In [31]:
# Fitting and Training the model
logic.fit(X_train, y_train)

LogisticRegression()

In [33]:
logic.predict(X_test)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [34]:
predict = logic.predict(X_test)

In [35]:
predict

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [37]:
accuracy_score(y_test, predict) * 100

56.00000000000001

In [60]:
f1_score(y_test, predict)

0.0

In [38]:
from sklearn.naive_bayes import GaussianNB

In [39]:
gaus = GaussianNB()

In [52]:
gaus.fit(X_train, y_train)

GaussianNB()

In [53]:
gaus.predict(X_test)

array([0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0], dtype=int64)

In [49]:
predicto = gaus.predict(X_test)

In [50]:
accuracy_score(y_test, predicto) * 100

86.0

In [61]:
f1_score(y_test, predicto)

0.8333333333333334

In [51]:
from sklearn.ensemble import RandomForestClassifier

In [46]:
rand = RandomForestClassifier()

In [54]:
rand.fit(X_train, y_train)

RandomForestClassifier()

In [55]:
rand.predict(X_test)

array([0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0], dtype=int64)

In [56]:
rain = rand.predict(X_test)

In [58]:
accuracy_score(y_test, rain) * 100

86.0

In [62]:
f1_score(y_test, rain)

0.8409090909090908

In [69]:
pokemonData.head()

#                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65   
1  2                Ivysaur  Grass  Poison  60      62       63       80   
2  3               Venusaur  Grass  Poison  80      82       83      100   
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122   
4  4             Charmander   Fire     NaN  39      52       43       60   

   Sp. Def  Speed  Generation  Legendary  
0       65     45           1      False  
1       80     60           1      False  
2      100     80           1      False  
3      120     80           1      False  
4       50     65           1      False

In [72]:
pokemonData["Legendary"] = pokemonData["Legendary"].apply(lambda x: 1 if x == "True" else 0)

In [73]:
pokemonData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   #           800 non-null    int64 
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   HP          800 non-null    int64 
 5   Attack      800 non-null    int64 
 6   Defense     800 non-null    int64 
 7   Sp. Atk     800 non-null    int64 
 8   Sp. Def     800 non-null    int64 
 9   Speed       800 non-null    int64 
 10  Generation  800 non-null    int64 
 11  Legendary   800 non-null    int64 
dtypes: int64(9), object(3)
memory usage: 75.1+ KB


In [74]:
# pokemonData.drop("#3")

In [75]:
pokemonData.head(10)

#                       Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1                  Bulbasaur  Grass  Poison  45      49       49       65   
1  2                    Ivysaur  Grass  Poison  60      62       63       80   
2  3                   Venusaur  Grass  Poison  80      82       83      100   
3  3      VenusaurMega Venusaur  Grass  Poison  80     100      123      122   
4  4                 Charmander   Fire     NaN  39      52       43       60   
5  5                 Charmeleon   Fire     NaN  58      64       58       80   
6  6                  Charizard   Fire  Flying  78      84       78      109   
7  6  CharizardMega Charizard X   Fire  Dragon  78     130      111      130   
8  6  CharizardMega Charizard Y   Fire  Flying  78     104       78      159   
9  7                   Squirtle  Water     NaN  44      48       65       50   

   Sp. Def  Speed  Generation  Legendary  
0       65     45           1          0  
1       80     60           1          0  
2      100     80           1          0  
3      120     80           1          0  
4       50     65           1          0  
5       65     80           1          0  
6       85    100           1          0  
7       85    100           1          0  
8      115    100           1          0  
9       64     43           1          0

In [83]:
pokemonData.drop("#", axis = "columns", inplace = True)
pokemonData.drop("Name", axis = "columns", inplace = True)
pokemonData.drop("Type 1", axis = "columns", inplace = True)
pokemonData.drop("Type 2", axis = "columns", inplace = True)


In [81]:
pokemonData.drop("Name", axis = "columns")

#   Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
0      1    Grass  Poison  45      49       49       65       65     45   
1      2    Grass  Poison  60      62       63       80       80     60   
2      3    Grass  Poison  80      82       83      100      100     80   
3      3    Grass  Poison  80     100      123      122      120     80   
4      4     Fire     NaN  39      52       43       60       50     65   
..   ...      ...     ...  ..     ...      ...      ...      ...    ...   
795  719     Rock   Fairy  50     100      150      100      150     50   
796  719     Rock   Fairy  50     160      110      160      110    110   
797  720  Psychic   Ghost  80     110       60      150      130     70   
798  720  Psychic    Dark  80     160       60      170      130     80   
799  721     Fire   Water  80     110      120      130       90     70   

     Generation  Legendary  
0             1          0  
1             1          0  
2             1          0  
3             1          0  
4             1          0  
..          ...        ...  
795           6          0  
796           6          0  
797           6          0  
798           6          0  
799           6          0  

[800 rows x 11 columns]

In [84]:
pokemonData.head()

HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
0  45      49       49       65       65     45           1          0
1  60      62       63       80       80     60           1          0
2  80      82       83      100      100     80           1          0
3  80     100      123      122      120     80           1          0
4  39      52       43       60       50     65           1          0

In [85]:
pokemonData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   HP          800 non-null    int64
 1   Attack      800 non-null    int64
 2   Defense     800 non-null    int64
 3   Sp. Atk     800 non-null    int64
 4   Sp. Def     800 non-null    int64
 5   Speed       800 non-null    int64
 6   Generation  800 non-null    int64
 7   Legendary   800 non-null    int64
dtypes: int64(8)
memory usage: 50.1 KB


In [87]:
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score

In [89]:
X_train, y_train, X_test, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1234, shuffle = True)

In [92]:
X = pokemonData.drop("Legendary", axis = "columns")

In [100]:
y = pokemonData["Legendary"]

In [90]:
logist = LogisticRegression()

In [94]:
X

HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation
0    45      49       49       65       65     45           1
1    60      62       63       80       80     60           1
2    80      82       83      100      100     80           1
3    80     100      123      122      120     80           1
4    39      52       43       60       50     65           1
..   ..     ...      ...      ...      ...    ...         ...
795  50     100      150      100      150     50           6
796  50     160      110      160      110    110           6
797  80     110       60      150      130     70           6
798  80     160       60      170      130     80           6
799  80     110      120      130       90     70           6

[800 rows x 7 columns]

In [95]:
y

0      0
1      0
2      0
3      0
4      0
      ..
795    0
796    0
797    0
798    0
799    0
Name: Legendary, Length: 800, dtype: int64

In [96]:
y_train

Gender  Age  EstimatedSalary
44        0   28            84000
110       0   39            71000
78        0   28            87000
181       0   31            71000
285       0   37            93000
..      ...  ...              ...
299       1   46           117000
55        0   24            55000
129       0   26            84000
153       0   36            50000
90        1   22            81000

[80 rows x 3 columns]

In [102]:
y_train

Gender  Age  EstimatedSalary
44        0   28            84000
110       0   39            71000
78        0   28            87000
181       0   31            71000
285       0   37            93000
..      ...  ...              ...
299       1   46           117000
55        0   24            55000
129       0   26            84000
153       0   36            50000
90        1   22            81000

[80 rows x 3 columns]

In [103]:
X_train

Gender  Age  EstimatedSalary
33        0   28            44000
253       0   37           146000
118       1   40            59000
300       0   58            38000
115       1   40            57000
..      ...  ...              ...
204       0   58           101000
53        0   35            23000
294       0   35            57000
211       1   52           150000
303       1   37            79000

[320 rows x 3 columns]